### ISSUE TITLE
直接clone后无法使用

### ISSUE THREAD

**Issue by Erchoc** [ElemeFE/vue-amap#137]
```
git clone https://github.com/ElemeFE/vue-amap.git

cd vue-amap && cnpm install

cnpm run dev


Install fail! RequestError: getaddrinfo ENOTFOUND cdn.npm.taobao.org cdn.npm.taobao.org:443 (req "error"), GET https://cdn.npm.taobao.org/selenium-server/-/selenium-server-2.53.1.tgz -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":35,"createSocketErrorCount":0,"closeSocketCount":34,"errorSocketCount":0,"timeoutSocketCount":18,"requestCount":1457,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":1},"requests":{}})
headers: {}
Error: getaddrinfo ENOTFOUND cdn.npm.taobao.org cdn.npm.taobao.org:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
npminstall version: 2.30.1
npminstall args: /usr/local/Cellar/node/7.10.0/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/erchoc/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

```

**Comment by MrSuperJ** [comment]
没有试过直接clone   可以尝试根据文档测试，   记得在main.js里部署

**Comment by jerry-i** [comment]
O__O "…感觉是你源的问题
